sudo: required
services:
  - docker

before_script:
  - docker build -t tmp_image -f Dockerfile.dev .

script:
  - docker run -e CI=true tmp_image npm run test
  - echo "$AWS_ACCESS_KEY"
  - echo "$AWS_SECRETE_KEY"

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-test-app"
  env: "DockerTestApp-env"
  bucket_name: "elasticbeanstalk-us-east-1-735458237462"
  bucket_path: "docker-test-app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRETE_KEY"